/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phonestore.GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import phonestore.BUS.UserBUS;
import phonestore.InformationLogin.InformationLogin;

/**
 *
 * @author congh
 */
public class DashBoard extends javax.swing.JFrame {
    public Color defaultColor, checkColor,disableColor;
    UserBUS userBUS=new UserBUS();

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setColor();
        setRole();
    }

    public void setColor() {
        defaultColor = new Color(0, 0, 0);
        checkColor = new Color(102, 102, 102);
        disableColor = new Color(255,255,255);

    }
    public void setRole(){
        int role= userBUS.getUserDTOByUserName(InformationLogin.getInstance().getUserName()).getrole_id();
            
        if(role==2){
                    jPanelBrand.removeAll();
                    jPanelGRN.removeAll();
                    jPanelProduct.removeAll();
                    jPanelRole.removeAll();
                    jPanelSupplier.removeAll();
                    jPanelUser.removeAll();
                    jPanelWarehouse.removeAll();
                    jPanelOrigin.removeAll();


        }
        else if (role==3) {
                    jPanelCustomer.removeAll();
                    jPanelInvoice.removeAll();
                    jPanelRole.removeAll();
                    jPanelUser.removeAll();
                    jPanelWarehouse.removeAll();
        }
        else{
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanelInvoice = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCustomer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelSupplier = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelProduct = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelBrand = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelOrigin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelRole = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelWarehouse = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelSaleStatistic = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelUser = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelGRN = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jPanel6.setBackground(new java.awt.Color(255, 0, 51));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Welcome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanelInvoice.setBackground(new java.awt.Color(0, 0, 0));
        jPanelInvoice.setPreferredSize(new java.awt.Dimension(159, 40));
        jPanelInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInvoiceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelInvoiceMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoice");

        javax.swing.GroupLayout jPanelInvoiceLayout = new javax.swing.GroupLayout(jPanelInvoice);
        jPanelInvoice.setLayout(jPanelInvoiceLayout);
        jPanelInvoiceLayout.setHorizontalGroup(
            jPanelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInvoiceLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelInvoiceLayout.setVerticalGroup(
            jPanelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelCustomer.setBackground(new java.awt.Color(0, 0, 0));
        jPanelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustomerMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCustomerMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer");

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelSupplier.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSupplierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSupplierMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Supplier");

        javax.swing.GroupLayout jPanelSupplierLayout = new javax.swing.GroupLayout(jPanelSupplier);
        jPanelSupplier.setLayout(jPanelSupplierLayout);
        jPanelSupplierLayout.setHorizontalGroup(
            jPanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSupplierLayout.setVerticalGroup(
            jPanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelProduct.setBackground(new java.awt.Color(0, 0, 0));
        jPanelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProductMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelProductMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product");

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelBrand.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBrandMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBrandMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Brand");

        javax.swing.GroupLayout jPanelBrandLayout = new javax.swing.GroupLayout(jPanelBrand);
        jPanelBrand.setLayout(jPanelBrandLayout);
        jPanelBrandLayout.setHorizontalGroup(
            jPanelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBrandLayout.setVerticalGroup(
            jPanelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelOrigin.setBackground(new java.awt.Color(0, 0, 0));
        jPanelOrigin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelOriginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelOriginMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Origin");

        javax.swing.GroupLayout jPanelOriginLayout = new javax.swing.GroupLayout(jPanelOrigin);
        jPanelOrigin.setLayout(jPanelOriginLayout);
        jPanelOriginLayout.setHorizontalGroup(
            jPanelOriginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelOriginLayout.setVerticalGroup(
            jPanelOriginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelRole.setBackground(new java.awt.Color(0, 0, 0));
        jPanelRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRoleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRoleMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Role");

        javax.swing.GroupLayout jPanelRoleLayout = new javax.swing.GroupLayout(jPanelRole);
        jPanelRole.setLayout(jPanelRoleLayout);
        jPanelRoleLayout.setHorizontalGroup(
            jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRoleLayout.setVerticalGroup(
            jPanelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelWarehouse.setBackground(new java.awt.Color(0, 0, 0));
        jPanelWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelWarehouseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelWarehouseMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Warehouse");

        javax.swing.GroupLayout jPanelWarehouseLayout = new javax.swing.GroupLayout(jPanelWarehouse);
        jPanelWarehouse.setLayout(jPanelWarehouseLayout);
        jPanelWarehouseLayout.setHorizontalGroup(
            jPanelWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelWarehouseLayout.setVerticalGroup(
            jPanelWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelSaleStatistic.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSaleStatistic.setPreferredSize(new java.awt.Dimension(159, 40));
        jPanelSaleStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSaleStatisticMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSaleStatisticMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sales Statistics");

        javax.swing.GroupLayout jPanelSaleStatisticLayout = new javax.swing.GroupLayout(jPanelSaleStatistic);
        jPanelSaleStatistic.setLayout(jPanelSaleStatisticLayout);
        jPanelSaleStatisticLayout.setHorizontalGroup(
            jPanelSaleStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSaleStatisticLayout.setVerticalGroup(
            jPanelSaleStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLogout.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLogoutMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Logout");

        javax.swing.GroupLayout jPanelLogoutLayout = new javax.swing.GroupLayout(jPanelLogout);
        jPanelLogout.setLayout(jPanelLogoutLayout);
        jPanelLogoutLayout.setHorizontalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLogoutLayout.setVerticalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelUser.setBackground(new java.awt.Color(0, 0, 0));
        jPanelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelUserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelUserMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User");

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelGRN.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGRN.setForeground(new java.awt.Color(255, 255, 255));
        jPanelGRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGRNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGRNMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GRN");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGRNLayout = new javax.swing.GroupLayout(jPanelGRN);
        jPanelGRN.setLayout(jPanelGRNLayout);
        jPanelGRNLayout.setHorizontalGroup(
            jPanelGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGRNLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelGRNLayout.setVerticalGroup(
            jPanelGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSaleStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelGRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanelInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanelBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSaleStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelRoleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRoleMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(checkColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }//GEN-LAST:event_jPanelRoleMousePressed

    private void jPanelUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUserMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(checkColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
        
    }//GEN-LAST:event_jPanelUserMousePressed

    private void jPanelRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRoleMouseClicked
        // TODO add your handling code here:
        Role1GUI role1GUI=new Role1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(role1GUI).setVisible(true);
    }//GEN-LAST:event_jPanelRoleMouseClicked
    // TODO add your handling code here:

    private void jPanelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUserMouseClicked
        // TODO add your handling code here:
        User1GUI user1GUI=new User1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(user1GUI).setVisible(true);
    }//GEN-LAST:event_jPanelUserMouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        GRN1GUI grn1gui=new GRN1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(grn1gui).setVisible(true);
                        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(checkColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);

    }//GEN-LAST:event_jLabel3MousePressed
    // TODO add your handling code here:

    private void jPanelGRNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGRNMousePressed
        // TODO add your handling code here:
                jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(checkColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);

    }//GEN-LAST:event_jPanelGRNMousePressed

    private void jPanelGRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGRNMouseClicked
        // TODO add your handling code here:
//        GRN1GUI grn1gui=new GRN1GUI();
//        jDesktopPane1.removeAll();
//        jDesktopPane1.add(grn1gui).setVisible(true);
    }//GEN-LAST:event_jPanelGRNMouseClicked

    

    private void jPanelInvoiceMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelInvoiceMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(checkColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelInvoiceMousePressed

    private void jPanelCustomerMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelCustomerMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(checkColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelCustomerMousePressed

    private void jPanelSupplierMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelSupplierMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(checkColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelSupplierMousePressed

    private void jPanelProductMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelProductMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(checkColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelProductMousePressed

    private void jPanelBrandMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelBrandMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(checkColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelBrandMousePressed

    private void jPanelOriginMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelOriginMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(checkColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelOriginMousePressed

    private void jPanelWarehouseMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelWarehouseMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(checkColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelWarehouseMousePressed

    private void jPanelSaleStatisticMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelSaleStatisticMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(checkColor);
        jPanelLogout.setBackground(defaultColor);
    }// GEN-LAST:event_jPanelSaleStatisticMousePressed

    private void jPanelLogoutMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelLogoutMousePressed
        // TODO add your handling code here:
        jPanelInvoice.setBackground(defaultColor);
        jPanelGRN.setBackground(defaultColor);
        jPanelCustomer.setBackground(defaultColor);
        jPanelSupplier.setBackground(defaultColor);
        jPanelProduct.setBackground(defaultColor);
        jPanelOrigin.setBackground(defaultColor);
        jPanelBrand.setBackground(defaultColor);
        jPanelUser.setBackground(defaultColor);
        jPanelWarehouse.setBackground(defaultColor);
        jPanelRole.setBackground(defaultColor);
        jPanelSaleStatistic.setBackground(defaultColor);
        jPanelLogout.setBackground(checkColor);
    }// GEN-LAST:event_jPanelLogoutMousePressed

    private void jPanelInvoiceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelInvoiceMouseClicked
        // TODO add your handling code here:
        Invoice1GUI invoice1GUI = new Invoice1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(invoice1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelInvoiceMouseClicked

    private void jPanelSupplierMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelSupplierMouseClicked
        // TODO add your handling code here:
        Supplier1GUI supplier1GUI = new Supplier1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(supplier1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelSupplierMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane, "do you want to exit?");
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }// GEN-LAST:event_jPanel6MouseClicked

    private void jPanelWarehouseMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelWarehouseMouseClicked
        // TODO add your handling code here:
        Warehouse1GUI warehouse1GUI = new Warehouse1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(warehouse1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelWarehouseMouseClicked

    private void jPanelSaleStatisticMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelSaleStatisticMouseClicked
        // TODO add your handling code here:
        Statistic1GUI statistic1GUI = new Statistic1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(statistic1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelSaleStatisticMouseClicked

    private void jPanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelLogoutMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane, "do you want do logout?");
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }// GEN-LAST:event_jPanelLogoutMouseClicked

    private void jPanelBrandMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelBrandMouseClicked
        // TODO add your handling code here:
        Brand1GUI brand1GUI = new Brand1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(brand1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelBrandMouseClicked

    private void jPanelProductMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelProductMouseClicked
        // TODO add your handling code here:
        Product1GUI product1GUI = new Product1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(product1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelProductMouseClicked

    private void jPanelCustomerMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelCustomerMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanelCustomerMouseEntered

    private void jPanelCustomerMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelCustomerMouseClicked
        // TODO add your handling code here:
        Customer1GUI customer1GUI = new Customer1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(customer1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelCustomerMouseClicked

    private void jPanelOriginMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelOriginMouseClicked
        // TODO add your handling code here:
        Origin1GUI origin1GUI = new Origin1GUI();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(origin1GUI).setVisible(true);
    }// GEN-LAST:event_jPanelOriginMouseClicked


    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBrand;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelGRN;
    private javax.swing.JPanel jPanelInvoice;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel jPanelOrigin;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JPanel jPanelRole;
    private javax.swing.JPanel jPanelSaleStatistic;
    private javax.swing.JPanel jPanelSupplier;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JPanel jPanelWarehouse;
    // End of variables declaration//GEN-END:variables
}
