/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package phonestore.GUI;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import phonestore.BUS.ProductBLL;
import phonestore.DTO.ProductDTO;

/**
 *
 * @author congh
 */
public class Product1GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form Product1GUI
     */
        ProductBLL productBLL = new ProductBLL();
    DefaultTableModel defaultTableModel;
    private String selectedImageName;
    private String currentDir = System.getProperty("user.dir");

    public Product1GUI() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
                defaultTableModel = (DefaultTableModel) jTableProduct.getModel();
        showAllData();

    }
    public void showAllData() {
        defaultTableModel.setRowCount(0);
        Vector<ProductDTO> arr = productBLL.getAllProducts();
        for (ProductDTO productDTO : arr) {
            Object[] objects = new Object[] { 
                productDTO.getProduct_id(), 
                productDTO.getProduct_name(),
                productDTO.getRam(), 
                productDTO.getRom(), 
                productDTO.getBattery_capacity(),
                productDTO.getChip(), 
                productDTO.getBrand_id(), 
                productDTO.getOrigin_id(),
                productDTO.getImage_path()
            };
            defaultTableModel.addRow(objects);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jLabeId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        textFieldName = new javax.swing.JTextField();
        jLabelEmal = new javax.swing.JLabel();
        textFieldRam = new javax.swing.JTextField();
        textFieldRom = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        textFieldBattery = new javax.swing.JTextField();
        textFieldChip = new javax.swing.JTextField();
        jLabelAddress1 = new javax.swing.JLabel();
        jLabelAddress2 = new javax.swing.JLabel();
        textFieldBrand = new javax.swing.JTextField();
        textFieldOrigin = new javax.swing.JTextField();
        jLabelAddress3 = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        textFieldLink = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddImg = new javax.swing.JButton();
        textfieldSearch = new javax.swing.JTextField();
        jbuttonExport = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Ram", "Rom", "Battery capacity", "Chip", "Brand ID", "Origin ID", "image"
            }
        ));
        jTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduct);

        jLabeId.setBackground(new java.awt.Color(255, 255, 255));
        jLabeId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabeId.setText("Id");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelName.setText("Name");

        textFieldId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelEmal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEmal.setText("Ram");

        textFieldRam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldRom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPhone.setText("Rom");

        jLabelAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAddress.setText("Battery capacity");

        textFieldBattery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldChip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelAddress1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAddress1.setText("Chip");

        jLabelAddress2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAddress2.setText("Brand ID");

        textFieldBrand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldOrigin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelAddress3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAddress3.setText("Origin ID");

        jLabelImg.setBackground(new java.awt.Color(255, 255, 255));
        jLabelImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLinkActionPerformed(evt);
            }
        });

        jLabel2.setText("LINK");

        jButtonAddImg.setBackground(new java.awt.Color(102, 204, 255));
        jButtonAddImg.setText("Choose Image");
        jButtonAddImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddImgActionPerformed(evt);
            }
        });

        textfieldSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jbuttonExport.setBackground(new java.awt.Color(102, 204, 255));
        jbuttonExport.setText("Export Excel");

        jButtonDelete.setBackground(new java.awt.Color(102, 204, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(102, 204, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(102, 204, 255));
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(102, 204, 255));
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonRefresh.setBackground(new java.awt.Color(102, 204, 255));
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(588, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddImg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(568, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldChip, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabeId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldName))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldBattery))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldRom))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelEmal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldRam)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                            .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(173, 173, 173))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbuttonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                    .addComponent(textfieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE))
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddImg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabeId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldId))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelEmal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldRam))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldRom))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldBattery)))
                        .addComponent(jLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldChip))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldBrand))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldOrigin))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbuttonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(100, 100, 100)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductMouseClicked
        // TODO add your handling code here:
                int row = jTableProduct.getSelectedRow();
        textFieldId.setText(defaultTableModel.getValueAt(row, 0).toString());
        textFieldName.setText(defaultTableModel.getValueAt(row, 1).toString());
        textFieldRam.setText(defaultTableModel.getValueAt(row, 2).toString());
        textFieldRom.setText(defaultTableModel.getValueAt(row, 3).toString());
        textFieldBattery.setText(defaultTableModel.getValueAt(row, 4).toString());
        textFieldChip.setText(defaultTableModel.getValueAt(row, 5).toString());
        textFieldBrand.setText(defaultTableModel.getValueAt(row, 6).toString());
        textFieldOrigin.setText(defaultTableModel.getValueAt(row, 7).toString());
        textFieldLink.setText(defaultTableModel.getValueAt(row, 8).toString());
        String imagePath = defaultTableModel.getValueAt(row, 8).toString();
        String absoluteImagePath = currentDir + "\\src\\main\\java\\phonestore\\" + imagePath;

        // Hiển thị hình ảnh trong jLabelImg
        try {
            File file = new File(absoluteImagePath);
            BufferedImage bufferedImage = ImageIO.read(file);
            Image image = bufferedImage.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            jLabelImg.setIcon(new ImageIcon(image));
        } catch (Exception e) {           
            JOptionPane.showMessageDialog(this, "Error loading image", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTableProductMouseClicked

    private void textFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLinkActionPerformed

    private void jButtonAddImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddImgActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int returnValue = fileChooser.showOpenDialog(this);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        selectedImageName = file.getName(); // Lấy tên tệp tin
        textFieldLink.setText(file.getAbsolutePath());
        BufferedImage bufferedImage;
        try {
            bufferedImage = ImageIO.read(file);
            Image image = bufferedImage.getScaledInstance(300, 300, Image.SCALE_SMOOTH);
            jLabelImg.setIcon(new ImageIcon(image));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "please choose file again", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonAddImgActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
                try {
            if (textFieldId.getText().trim().equals("") || 
                textFieldName.getText().trim().equals("") || 
                textFieldRam.getText().trim().equals("") || 
                textFieldRom.getText().trim().equals("") || 
                textFieldBattery.getText().trim().equals("") || 
                textFieldChip.getText().trim().equals("") || 
                textFieldBrand.getText().trim().equals("") || 
                textFieldOrigin.getText().trim().equals("") || 
                jLabelImg.getIcon() == null) {
                JOptionPane.showMessageDialog(this, "Please enter all required information");
            } else {
                ProductDTO pro = new ProductDTO();
                pro.setProduct_id(Integer.parseInt(textFieldId.getText()));
                pro.setProduct_name(textFieldName.getText());
                pro.setRam(textFieldRam.getText());
                pro.setRom(textFieldRom.getText());
                pro.setBattery_capacity(textFieldBattery.getText());
                pro.setChip(textFieldChip.getText());
                pro.setBrand_id(Integer.parseInt(textFieldBrand.getText()));
                pro.setOrigin_id(Integer.parseInt(textFieldOrigin.getText()));
                pro.setStatus("disable");
                JOptionPane.showMessageDialog(this, productBLL.deleteProduct(pro));
                defaultTableModel.setRowCount(0);
                showAllData();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid information");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if(textFieldId.getText().trim().equals("") || textFieldName.getText().trim().equals("") || textFieldRam.getText().trim().equals("") || textFieldRom.getText().trim().equals("") || textFieldBattery.getText().trim().equals("") || textFieldChip.getText().trim().equals("") || textFieldBrand.getText().trim().equals("") || textFieldOrigin.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter all required information");
            } else {
                ProductDTO productDTO = new ProductDTO();
                productDTO.setProduct_id(Integer.parseInt(textFieldId.getText()));
                productDTO.setProduct_name(textFieldName.getText());
                productDTO.setRam(textFieldRam.getText());
                productDTO.setRom(textFieldRom.getText());
                productDTO.setBattery_capacity(textFieldBattery.getText());
                productDTO.setChip(textFieldChip.getText());
                productDTO.setBrand_id(Integer.parseInt(textFieldBrand.getText()));
                productDTO.setOrigin_id(Integer.parseInt(textFieldOrigin.getText()));
                productDTO.setStatus("active");
                // Thêm code cập nhật đường dẫn ảnh
                String relativeImagePath = "IMAGE\\" + selectedImageName;
                productDTO.setImage_path(relativeImagePath);
                // Kết thúc thêm code cập nhật đường dẫn ảnh
                JOptionPane.showMessageDialog(this, productBLL.updateProduct(productDTO));
                showAllData();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid information");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
                try {
            if(textFieldId.getText().trim().equals("") || textFieldName.getText().trim().equals("") || textFieldRam.getText().trim().equals("") || textFieldRom.getText().trim().equals("") || textFieldBattery.getText().trim().equals("") || textFieldChip.getText().trim().equals("") || textFieldBrand.getText().trim().equals("") || textFieldOrigin.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter all required information");
            } else {
                ProductDTO productDTO = new ProductDTO();
                productDTO.setProduct_id(Integer.parseInt(textFieldId.getText()));
                productDTO.setProduct_name(textFieldName.getText());
                productDTO.setRam(textFieldRam.getText());
                productDTO.setRom(textFieldRom.getText());
                productDTO.setBattery_capacity(textFieldBattery.getText());
                productDTO.setChip(textFieldChip.getText());
                productDTO.setBrand_id(Integer.parseInt(textFieldBrand.getText()));
                productDTO.setOrigin_id(Integer.parseInt(textFieldOrigin.getText()));
                productDTO.setStatus("active");           
                String relativeImagePath = "IMAGE\\" + selectedImageName;
                productDTO.setImage_path(relativeImagePath);               
                JOptionPane.showMessageDialog(this, productBLL.addProduct(productDTO));
                showAllData();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid information");
        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
                String searchText = textfieldSearch.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a search keyword", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Vector<ProductDTO> searchResult = productBLL.searchProduct(searchText);
        if (searchResult.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No products found", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        defaultTableModel.setRowCount(0);
        for (ProductDTO pro : searchResult) {
            Object[] row = {pro.getProduct_id(), pro.getProduct_name(), pro.getRam(), pro.getRom(), pro.getBattery_capacity(), pro.getChip(), pro.getBrand_id(), pro.getOrigin_id(), pro.getImage_path()};
            defaultTableModel.addRow(row);
        }

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        showAllData();
    }//GEN-LAST:event_jButtonRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddImg;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabeId;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelAddress2;
    private javax.swing.JLabel jLabelAddress3;
    private javax.swing.JLabel jLabelEmal;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JButton jbuttonExport;
    private javax.swing.JTextField textFieldBattery;
    private javax.swing.JTextField textFieldBrand;
    private javax.swing.JTextField textFieldChip;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldLink;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldOrigin;
    private javax.swing.JTextField textFieldRam;
    private javax.swing.JTextField textFieldRom;
    private javax.swing.JTextField textfieldSearch;
    // End of variables declaration//GEN-END:variables
}
