/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package phonestore.GUI;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;

//import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import phonestore.BUS.StatisticBUS;
import phonestore.DAO.ProductDAL;
import phonestore.DAO.StatistisDAO;
import phonestore.DTO.StatistisDTO;
import phonestore.DTO.invoiceDetailDTO;

/**
 *
 * @author congh
 */
public class Statistic1GUI extends javax.swing.JInternalFrame {
        DefaultTableModel productdeDefaultTableModel, invoiceDefaultTableModel;
    StatisticBUS statisticBUS=new StatisticBUS();
    StatistisDAO statistisDAO=new StatistisDAO();
    ProductDAL productDAL=new ProductDAL();
    TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form Statistic1GUI
     */
    public Statistic1GUI() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
                productdeDefaultTableModel= (DefaultTableModel) jTableProduct.getModel();
        invoiceDefaultTableModel= (DefaultTableModel) jTableInvoice.getModel();
        showAllDataProduct(null,null);
        showTotalProduct(null,null);
        showAllDataInvoice(null);
        showTotalInvoice(null);
        sorter=new TableRowSorter<>(productdeDefaultTableModel);
        jTableProduct.setRowSorter(sorter);
        jTableInvoice.setRowSorter(sorter);
        jTableProduct.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableInvoice.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    public void showAllDataProduct(String fromDate,String toDate){
        productdeDefaultTableModel.setRowCount(0);
        for(StatistisDTO statistisDTO:statistisDAO.getArrProductByDateAndDate(fromDate, toDate)){
            Object[] objects=new Object[]{
                statistisDTO.getProductID(), productDAL.getProductbyID(statistisDTO.getProductID()).getProduct_name(),
                statistisDTO.getTotalQuantity(),statistisDTO.getTotalPrice()
            };
            productdeDefaultTableModel.addRow(objects);
        }
    }
    public void showAllDataInvoice(String date){
        invoiceDefaultTableModel.setRowCount(0);
        for(invoiceDetailDTO inDTO: statistisDAO.getArrInvoiceByDate(date)){
            Object[] objects=new Object[]{
                inDTO.getProductId(),productDAL.getProductbyID(inDTO.getProductId()).getProduct_name(),
                inDTO.getQuantity(),inDTO.getPrice()
            };
            invoiceDefaultTableModel.addRow(objects);
        }
    }
    public void showTotalInvoice(String date){
        jLabeltongdoanhthumotngay.setText(Integer.toString(statisticBUS.getTotalPriceinvoice(date)));
        jLabeltongsoluongmotngay.setText(Integer.toString(statisticBUS.getTotalQuantityInvoice(date)));
    }
    public void showTotalProduct(String fromDate, String toDate){
        jLabelTongsoluongsanpham.setText(Integer.toString(statisticBUS.getTotalQuantityProduct(fromDate, toDate)));
        jLabelTongdoanhthusanpham.setText(Integer.toString(statisticBUS.getTotalPriceProduct(fromDate, toDate)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserProductTo = new com.toedter.calendar.JDateChooser();
        jDateChooserProductFrom = new com.toedter.calendar.JDateChooser();
        jButtonSearchProduct = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelTongdoanhthusanpham = new javax.swing.JLabel();
        jLabelTongsoluongsanpham = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jButtonRefreshProduct = new javax.swing.JButton();
        jButtonExportExcelProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInvoice = new javax.swing.JTable();
        jDateChooserInvoice = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonSearchInvoice = new javax.swing.JButton();
        jButtonRefreshInvoice = new javax.swing.JButton();
        jLabeltongdoanhthumotngay = new javax.swing.JLabel();
        jLabeltongsoluongmotngay = new javax.swing.JLabel();
        jButtonExportExcel = new javax.swing.JButton();

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("To");
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 15));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("From");
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 15));

        jDateChooserProductTo.setDateFormatString("yyyy-MM-dd");

        jDateChooserProductFrom.setDateFormatString("yyyy-MM-dd");

        jButtonSearchProduct.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSearchProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchProduct.setText("Search");
        jButtonSearchProduct.setPreferredSize(new java.awt.Dimension(40, 15));
        jButtonSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchProductActionPerformed(evt);
            }
        });

        jLabel12.setText("quantity of products sold");
        jLabel12.setPreferredSize(new java.awt.Dimension(40, 15));

        jLabel13.setText("total revenue");
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 15));

        jLabelTongdoanhthusanpham.setPreferredSize(new java.awt.Dimension(40, 15));

        jLabelTongsoluongsanpham.setPreferredSize(new java.awt.Dimension(40, 15));

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Phone ID", "Phone Name", "Total quantity", "Total amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProduct);

        jButtonRefreshProduct.setBackground(new java.awt.Color(0, 102, 102));
        jButtonRefreshProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefreshProduct.setText("Refresh");
        jButtonRefreshProduct.setPreferredSize(new java.awt.Dimension(40, 15));
        jButtonRefreshProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshProductActionPerformed(evt);
            }
        });

        jButtonExportExcelProduct.setBackground(new java.awt.Color(0, 102, 102));
        jButtonExportExcelProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExportExcelProduct.setText("Export Excel");
        jButtonExportExcelProduct.setPreferredSize(new java.awt.Dimension(40, 15));
        jButtonExportExcelProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportExcelProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTongdoanhthusanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTongsoluongsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExportExcelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserProductFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserProductTo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonRefreshProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserProductTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jDateChooserProductFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButtonSearchProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRefreshProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTongdoanhthusanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTongsoluongsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonExportExcelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Product", jPanel2);

        jTableInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Phone ID", "Phone Name", "Quantity", "price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableInvoice);

        jDateChooserInvoice.setDateFormatString("yyyy-MM-dd");

        jLabel14.setText("total revenue");
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 15));

        jLabel15.setText("quantity of products sold");
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 15));

        jButtonSearchInvoice.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSearchInvoice.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchInvoice.setText("Search");
        jButtonSearchInvoice.setPreferredSize(new java.awt.Dimension(40, 15));
        jButtonSearchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchInvoiceActionPerformed(evt);
            }
        });

        jButtonRefreshInvoice.setBackground(new java.awt.Color(0, 102, 102));
        jButtonRefreshInvoice.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefreshInvoice.setText("Refresh");
        jButtonRefreshInvoice.setPreferredSize(new java.awt.Dimension(40, 15));
        jButtonRefreshInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshInvoiceActionPerformed(evt);
            }
        });

        jButtonExportExcel.setBackground(new java.awt.Color(0, 102, 102));
        jButtonExportExcel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExportExcel.setText("Export Excel");
        jButtonExportExcel.setPreferredSize(new java.awt.Dimension(40, 15));
        jButtonExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDateChooserInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonRefreshInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabeltongdoanhthumotngay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabeltongsoluongmotngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRefreshInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeltongdoanhthumotngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabeltongsoluongmotngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Invoice", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchProductActionPerformed
        // TODO add your handling code here:
        String fromDate =null,toDate =null;
        SimpleDateFormat simpleDateFormat=new SimpleDateFormat("yyyy-MM-dd");
        try {
            fromDate= simpleDateFormat.format(jDateChooserProductFrom.getDate());
            toDate= simpleDateFormat.format(jDateChooserProductTo.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select full dates");
        }
        showAllDataProduct(fromDate, toDate);
        showTotalProduct(fromDate, toDate);
    }//GEN-LAST:event_jButtonSearchProductActionPerformed

    private void jButtonRefreshProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshProductActionPerformed
        // TODO add your handling code here:
        showAllDataProduct(null, null);
        showTotalProduct(null, null);
    }//GEN-LAST:event_jButtonRefreshProductActionPerformed

    private void jButtonSearchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchInvoiceActionPerformed
        // TODO add your handling code here:
        String date="";
        SimpleDateFormat simpleDateFormat=new SimpleDateFormat("yyyy-MM-dd");
        try {
            date= simpleDateFormat.format(jDateChooserInvoice.getDate());
        } catch (Exception e) {
            e.printStackTrace();
        }
        showAllDataInvoice(date);
        showTotalInvoice(date);
        
    }//GEN-LAST:event_jButtonSearchInvoiceActionPerformed

    private void jButtonRefreshInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshInvoiceActionPerformed
        // TODO add your handling code here:
        showAllDataInvoice(null);
        showTotalInvoice(null);
    }//GEN-LAST:event_jButtonRefreshInvoiceActionPerformed

    private void jButtonExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportExcelActionPerformed
//         TODO add your handling code here:
        boolean check=false;
        JFileChooser fileChooser=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("EXCEL Files", "xlsx");
        fileChooser.setFileFilter(filter);
        int result= fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getPath()+".xlsx";
            Date date=jDateChooserInvoice.getDate();
            check=statisticBUS.ExportExcel(path, date);
        }
        if (check) {
            JOptionPane.showMessageDialog(rootPane, "export excel success");
        }else{
            JOptionPane.showMessageDialog(rootPane, "error");
        }
    }//GEN-LAST:event_jButtonExportExcelActionPerformed

    private void jButtonExportExcelProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportExcelProductActionPerformed
        // TODO add your handling code here:
        boolean check=false;
        JFileChooser fileChooser=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("EXCEL FILES", "xlsx");
        fileChooser.setFileFilter(filter);
        int resutl=fileChooser.showSaveDialog(jPanel1);
        if (resutl==JFileChooser.APPROVE_OPTION) {
            String path =fileChooser.getSelectedFile().getPath()+".xlsx";
            Date fromDate = jDateChooserProductFrom.getDate();
            Date toDate = jDateChooserProductTo.getDate();
            check = statisticBUS.ExportExcel(path, fromDate, toDate);
        }
        if(check){
            JOptionPane.showMessageDialog(rootPane, "export Excel success");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_jButtonExportExcelProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExportExcel;
    private javax.swing.JButton jButtonExportExcelProduct;
    private javax.swing.JButton jButtonRefreshInvoice;
    private javax.swing.JButton jButtonRefreshProduct;
    private javax.swing.JButton jButtonSearchInvoice;
    private javax.swing.JButton jButtonSearchProduct;
    private com.toedter.calendar.JDateChooser jDateChooserInvoice;
    private com.toedter.calendar.JDateChooser jDateChooserProductFrom;
    private com.toedter.calendar.JDateChooser jDateChooserProductTo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTongdoanhthusanpham;
    private javax.swing.JLabel jLabelTongsoluongsanpham;
    private javax.swing.JLabel jLabeltongdoanhthumotngay;
    private javax.swing.JLabel jLabeltongsoluongmotngay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableInvoice;
    private javax.swing.JTable jTableProduct;
    // End of variables declaration//GEN-END:variables
}
