/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phonestore.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import phonestore.BUS.SuplierBUS;
import phonestore.DTO.SuplierDTO;

/**
 *
 * @author congh
 */
public final class SupplierGUI extends javax.swing.JFrame {
        public ArrayList<SuplierDTO> arr;
        public SuplierBUS suplierBUS = new SuplierBUS();
        DefaultTableModel defaultTableModel;

        /**
         * Creates new form MenuGUI
         */
        public SupplierGUI() {
                initComponents();
                arr = new ArrayList<>();
                defaultTableModel = (DefaultTableModel) jTableSuplier.getModel();
                showAllData();
                setLocationRelativeTo(null);
        }

        public void showAllData() {
                defaultTableModel.setRowCount(0);
                arr = suplierBUS.getAllSuplier();
                for (SuplierDTO suplierDTO : arr) {
                        Object[] object = new Object[] {
                                        suplierDTO.getSuplierId(), suplierDTO.getSuplierName(),
                                        suplierDTO.getEmailAddress(), suplierDTO.getPhoneNumber(),
                                        suplierDTO.getAddress()
                        };
                        defaultTableModel.addRow(object);
                }
        }

        public void showDataSuplier(int row) {
                ArrayList<SuplierDTO> arrSearch = ArrObjectInTable();
                SuplierDTO suplierDTO = arrSearch.get(row);
                textFieldId.setText(Integer.toString(suplierDTO.getSuplierId()));
                textFieldName.setText(suplierDTO.getSuplierName());
                textFieldPhone.setText(suplierDTO.getPhoneNumber());
                textFieldEmail.setText(suplierDTO.getEmailAddress());
                textFieldAddress.setText(suplierDTO.getAddress());
        }

        public void showDataSearch(ArrayList<SuplierDTO> suplierDTOs) {
                defaultTableModel.setRowCount(0);
                ArrayList<SuplierDTO> arrSearch = suplierDTOs;
                for (SuplierDTO suplierDTO : arrSearch) {
                        Object[] object = new Object[] {
                                        suplierDTO.getSuplierId(), suplierDTO.getSuplierName(),
                                        suplierDTO.getEmailAddress(), suplierDTO.getPhoneNumber(),
                                        suplierDTO.getAddress()
                        };
                        defaultTableModel.addRow(object);
                }
        }

        public ArrayList<SuplierDTO> ArrObjectInTable() {
                int rowcount = defaultTableModel.getRowCount();
                ArrayList<SuplierDTO> arr = new ArrayList<>();
                for (int i = 0; i < rowcount; i++) {
                        Object id = defaultTableModel.getValueAt(i, 0);
                        Object name = defaultTableModel.getValueAt(i, 1);
                        Object emai = defaultTableModel.getValueAt(i, 2);
                        Object phone = defaultTableModel.getValueAt(i, 3);
                        Object address = defaultTableModel.getValueAt(i, 4);
                        SuplierDTO suplierDTO = new SuplierDTO(Integer.parseInt(id.toString()), name.toString(),
                                        emai.toString(), phone.toString(), address.toString(), 1);
                        arr.add(suplierDTO);
                }
                return arr;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTableSuplier = new javax.swing.JTable();
                jButtonAdd = new javax.swing.JButton();
                jButtonUpdate = new javax.swing.JButton();
                jButtonDelete = new javax.swing.JButton();
                jTextFieldSearch = new javax.swing.JTextField();
                jButtonSearch = new javax.swing.JButton();
                jButtonRefresh = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                textFieldId = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                textFieldName = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                textFieldPhone = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                textFieldEmail = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                textFieldAddress = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jTableSuplier.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "ID", "NAME", "EMAIL", "PHONE", "ADDRRESS"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class,
                                        java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jTableSuplier.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTableSuplierMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(jTableSuplier);

                jButtonAdd.setText("add");
                jButtonAdd.setToolTipText("");
                jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonAddActionPerformed(evt);
                        }
                });

                jButtonUpdate.setText("update");
                jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonUpdateActionPerformed(evt);
                        }
                });

                jButtonDelete.setText("delete");
                jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonDeleteActionPerformed(evt);
                        }
                });

                jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldSearchActionPerformed(evt);
                        }
                });

                jButtonSearch.setText("Search");
                jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonSearchActionPerformed(evt);
                        }
                });

                jButtonRefresh.setText("Refresh");
                jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRefreshActionPerformed(evt);
                        }
                });

                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("id");

                textFieldId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldIdActionPerformed(evt);
                        }
                });

                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("name");

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("phone");

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("email");

                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("address");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jButtonAdd,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                124,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(33, 33, 33)
                                                                                                                                .addComponent(jButtonUpdate,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                123,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(28, 28, 28)
                                                                                                                                .addComponent(jButtonDelete,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                118,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                81,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(textFieldId)
                                                                                                                                .addGap(119, 119,
                                                                                                                                                119)))
                                                                                                .addGap(233, 233, 233)
                                                                                                .addComponent(jTextFieldSearch,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                240,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(26, 26, 26)
                                                                                                .addComponent(jButtonSearch,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                76,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jButtonRefresh))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel5,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                81,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(12, 12, 12)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(textFieldName)
                                                                                                                                .addComponent(textFieldPhone)
                                                                                                                                .addComponent(textFieldAddress,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                214,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addComponent(textFieldEmail,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                214,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                798,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(jButtonDelete,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jButtonRefresh,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                38,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButtonSearch,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                38,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addComponent(jTextFieldSearch)
                                                                                                .addComponent(jButtonAdd,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addComponent(jButtonUpdate,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                38,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(26, 26, 26)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(textFieldId,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                43,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(textFieldName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                43,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(textFieldEmail,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(textFieldPhone,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel5,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(textFieldAddress,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addContainerGap())
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                535,
                                                                                                                Short.MAX_VALUE)))));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAddActionPerformed
                int id = Integer.parseInt(textFieldId.getText());
                String nameString = textFieldName.getText();
                String phoneString = textFieldPhone.getText();
                String emailString = textFieldEmail.getText();
                String addressString = textFieldAddress.getText();
                SuplierDTO suplierDTO = new SuplierDTO(id, nameString, emailString, phoneString, addressString, 1);
                suplierBUS.add_suplier(suplierDTO);
                showAllData();
        }// GEN-LAST:event_jButtonAddActionPerformed

        private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUpdateActionPerformed
                // TODO add your handling code here:
                int id = Integer.parseInt(textFieldId.getText());
                String nameString = textFieldName.getText();
                String phoneString = textFieldPhone.getText();
                String emailString = textFieldEmail.getText();
                String addressString = textFieldAddress.getText();
                SuplierDTO suplierDTO = new SuplierDTO(id, nameString, emailString, phoneString, addressString, 1);
                suplierBUS.update_suplier(suplierDTO);
                showAllData();
        }// GEN-LAST:event_jButtonUpdateActionPerformed

        private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSearchActionPerformed
                // TODO add your handling code here:
                String searString = jTextFieldSearch.getText();
                ArrayList<SuplierDTO> arrayList = suplierBUS.arr_search_suplier(searString);
                showDataSearch(arrayList);
        }// GEN-LAST:event_jButtonSearchActionPerformed

        private void textFieldIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldIdActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_textFieldIdActionPerformed

        private void jTableSuplierMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableSuplierMouseClicked
                int row = jTableSuplier.getSelectedRow();
                showDataSuplier(row);
        }// GEN-LAST:event_jTableSuplierMouseClicked

        private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDeleteActionPerformed
                // TODO add your handling code here:
                try {
                        suplierBUS.delete_suplier(Integer.parseInt(textFieldId.getText()));
                        showAllData();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                }
        }// GEN-LAST:event_jButtonDeleteActionPerformed

        private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldSearchActionPerformed
                // TODO add your handling code here:

        }// GEN-LAST:event_jTextFieldSearchActionPerformed

        private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRefreshActionPerformed
                // TODO add your handling code here:
                jTextFieldSearch.setText("");
                showAllData();
        }// GEN-LAST:event_jButtonRefreshActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new SupplierGUI().setVisible(true);

                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonAdd;
        private javax.swing.JButton jButtonDelete;
        private javax.swing.JButton jButtonRefresh;
        private javax.swing.JButton jButtonSearch;
        private javax.swing.JButton jButtonUpdate;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTableSuplier;
        private javax.swing.JTextField jTextFieldSearch;
        private javax.swing.JTextField textFieldAddress;
        private javax.swing.JTextField textFieldEmail;
        private javax.swing.JTextField textFieldId;
        private javax.swing.JTextField textFieldName;
        private javax.swing.JTextField textFieldPhone;
        // End of variables declaration//GEN-END:variables
}
